config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/biqwen2_5_1ep_colpali_train_6neg_128bs_2e4
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.BiQwen2_5_Processor
    pretrained_model_name_or_path:  "Qwen/Qwen2.5-VL-3B-Instruct" # "./models/paligemma-3b-mix-448"
    # num_image_tokens: 2048
    # max_length: 50
  num_negatives: 6 

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.BiQwen2_5
    pretrained_model_name_or_path: "Qwen/Qwen2.5-VL-3B-Instruct"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_train_set_ir_negs
  eval_dataset_loader: !import ../data/test_data.yaml

  # max_length: 50
  run_eval: true
  loss_func:
    (): colpali_engine.loss.bi_encoder_losses.BiEncoderLoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1 
    # this is global batch size 
    per_device_train_batch_size: 128 
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    ddp_find_unused_parameters: false
    resume_from_checkpoint: false
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 16
    eval_strategy: "no"
    dataloader_num_workers: 0
    log_level: "info"
    accelerator_config:
      split_batches: true
    # bf16: true
    save_steps: 500
    logging_steps: 10
    eval_steps: 100
    warmup_ratio: 0.01
    learning_rate: 2e-4
    save_total_limit: 1
    # resume_from_checkpoint: true
    optim: "paged_adamw_8bit"
    # wandb logging
    run_name: "biqwen2_5_1ep_colpali_train_6neg_128bs_2e4"
    report_to: "wandb"


  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'